FROM java:8
MAINTAINER fw-cloud-framework <liuweijw.github@foxmail.com>

ADD ../../fw-cloud-business/fw-cloud-business-admin/target/fw-cloud-business-admin.jar /app/

CMD ["java", "-Xmx300m", "-jar", "/app/fw-cloud-business-admin.jar"]

EXPOSE 2002
